In [3]:
import pandas as pd

# Load the raw dataset
df = pd.read_excel("../data/raw/Online Retail.xlsx")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/Online Retail.xlsx'

In [2]:
import os

for root, dirs, files in os.walk(".."):
    for file in files:
        if file.lower().endswith((".xlsx", ".xls", ".csv")):
            print(os.path.join(root, file))

..\ecommerce-data-pipeline\.venv\Lib\site-packages\matplotlib\mpl-data\sample_data\data_x_x2_x3.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\matplotlib\mpl-data\sample_data\msft.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\matplotlib\mpl-data\sample_data\Stocks.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\mt19937-testset-2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\pcg64-testset-2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\pcg64dxsm-testset-2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\philox-testset-2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\random\tests\data\sfc64-testset-2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccos.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arccosh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsin.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arcsinh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctan.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-arctanh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cbrt.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cos.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-cosh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-exp2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-expm1.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log10.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log1p.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-log2.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sin.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-sinh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tan.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\numpy\_core\tests\data\umath-validation-set-tanh.csv
..\ecommerce-data-pipeline\.venv\Lib\site-packages\tornado\test\csv_translations\fr_FR.csv
..\ecommerce-data-pipeline\data\raw\Online Retail.xlsx
..\Project 1\books_prices_multi.csv

In [4]:
import pandas as pd

# Load the raw dataset
df = pd.read_excel("../data/raw/Online Retail.xlsx")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/Online Retail.xlsx'

In [5]:
import os

print("Current folder:")
print(os.getcwd())

Current folder:
C:\Users\Administrator\Desktop\ecommerce-data-pipeline

In [17]:
import pandas as pd

# Load the raw dataset
df = pd.read_excel("data/raw/Online Retail.xlsx")

print("Dataset loaded successfully!") 
print("Shape:", df.shape)

print("\nColumns:")
print(df.columns.tolist())

print("\nFirst 5 rows:")
df.head()

Dataset loaded successfully!
Shape: (541909, 8)

Columns:
['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'UnitPrice', 'CustomerID', 'Country']

First 5 rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [18]:
# Check missing values
missing_values = df.isnull().sum()

print("Missing values per column:")
print(missing_values)

Missing values per column:
InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [19]:
# Check for duplicate rows
duplicates = df.duplicated().sum()

print("Number of duplicate rows:", duplicates)

Number of duplicate rows: 5268

In [20]:
# Check quantity statistics
print("Minimum quantity:", df["Quantity"].min())
print("Maximum quantity:", df["Quantity"].max())
print("Negative quantity rows:", (df["Quantity"] < 0).sum())
print("Zero quantity rows:", (df["Quantity"] == 0).sum())

Minimum quantity: -80995
Maximum quantity: 80995
Negative quantity rows: 10624
Zero quantity rows: 0

In [21]:
# Check cancelled invoices
cancelled_invoices = df["InvoiceNo"].astype(str).str.startswith("C")

print("Cancelled invoice rows:", cancelled_invoices.sum())
print("Negative quantity rows:", (df["Quantity"] < 0).sum())

print("\nExamples of cancelled invoices:")
print(df.loc[cancelled_invoices].head())

Cancelled invoice rows: 9288
Negative quantity rows: 10624

Examples of cancelled invoices:
    InvoiceNo StockCode                       Description  Quantity  \
141   C536379         D                          Discount        -1
154   C536383    35004C   SET OF 3 COLOURED  FLYING DUCKS        -1
235   C536391     22556    PLASTERS IN TIN CIRCUS PARADE        -12
236   C536391     21984  PACK OF 12 PINK PAISLEY TISSUES        -24
237   C536391     21983  PACK OF 12 BLUE PAISLEY TISSUES        -24

            InvoiceDate  UnitPrice  CustomerID         Country
141 2010-12-01 09:41:00      27.50     14527.0  United Kingdom
154 2010-12-01 09:49:00       4.65     15311.0  United Kingdom
235 2010-12-01 10:24:00       1.65     17548.0  United Kingdom
236 2010-12-01 10:24:00       0.29     17548.0  United Kingdom
237 2010-12-01 10:24:00       0.29     17548.0  United Kingdom

In [22]:
# Check unit price values

print("Minimum UnitPrice:", df["UnitPrice"].min())
print("Maximum UnitPrice:", df["UnitPrice"].max())
print("Zero UnitPrice rows:", (df["UnitPrice"] == 0).sum())
print("Negative UnitPrice rows:", (df["UnitPrice"] < 0).sum())

Minimum UnitPrice: -11062.06
Maximum UnitPrice: 38970.0
Zero UnitPrice rows: 2515
Negative UnitPrice rows: 2

In [23]:
# Inspect rows with negative UnitPrice
negative_price = df[df["UnitPrice"] < 0]

print(negative_price)

       InvoiceNo StockCode      Description  Quantity         InvoiceDate  \
299983   A563186         B  Adjust bad debt         1 2011-08-12 14:51:00
299984   A563187         B  Adjust bad debt         1 2011-08-12 14:52:00

        UnitPrice  CustomerID         Country
299983  -11062.06         NaN  United Kingdom
299984  -11062.06         NaN  United Kingdom

In [24]:
# Inspect rows with zero UnitPrice
zero_price = df[df["UnitPrice"] == 0]

print("Number of zero-price rows:", len(zero_price))
print("\nSample of zero-price rows:")
display(zero_price.head(20))

Number of zero-price rows: 2515

Sample of zero-price rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom

In [25]:
# Inspect zero-price transactions
zero_price = df[df["UnitPrice"] == 0]

print("Number of zero-price rows:", len(zero_price))

print("\nDescriptions:")
print(zero_price["Description"].value_counts().head(20))

print("\nSample rows:")
display(zero_price.head(20))

Number of zero-price rows: 2515

Descriptions:
Description
check                              159
?                                   47
damages                             45
damaged                             43
found                               25
sold as set on dotcom               20
adjustment                          16
Damaged                             14
FRENCH BLUE METAL DOOR SIGN 1        9
thrown away                          9
Unsaleable, destroyed.               9
amazon                               8
FRENCH BLUE METAL DOOR SIGN 8        8
Found                                8
FRENCH BLUE METAL DOOR SIGN 4        7
FRENCH BLUE METAL DOOR SIGN No       7
OWL DOORSTOP                         7
FRENCH BLUE METAL DOOR SIGN 3        7
RECIPE BOX PANTRY YELLOW DESIGN      7
??                                   7
Name: count, dtype: int64

Sample rows:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom

In [26]:
# Analyze quantities of zero-price transactions

print("Quantity distribution for zero-price rows:")
print(zero_price["Quantity"].value_counts().head(20))

print("\nPositive quantity:", (zero_price["Quantity"] > 0).sum())
print("Negative quantity:", (zero_price["Quantity"] < 0).sum())
print("Zero quantity:", (zero_price["Quantity"] == 0).sum())

Quantity distribution for zero-price rows:
Quantity
 1     402
 2     130
 3      84
-1      79
-2      58
-5      46
 4      42
 5      40
-3      39
-6      36
-4      35
-30     32
-9      32
-10     29
 6      29
-7      25
-21     24
 10     22
 8      21
-8      21
Name: count, dtype: int64

Positive quantity: 1179
Negative quantity: 1336
Zero quantity: 0

In [27]:
# Inspect zero-price rows with positive quantities

zero_price_positive = zero_price[zero_price["Quantity"] > 0]

print("Zero-price + positive quantity:", len(zero_price_positive))

print("\nDescriptions:")
print(zero_price_positive["Description"].value_counts().head(20))

print("\nSample:")
display(zero_price_positive.head(20))

Zero-price + positive quantity: 1179

Descriptions:
Description
check                              39
found                              25
adjustment                         14
FRENCH BLUE METAL DOOR SIGN 1       9
amazon                              8
FRENCH BLUE METAL DOOR SIGN 8       8
Found                               8
FRENCH BLUE METAL DOOR SIGN 4       7
FRENCH BLUE METAL DOOR SIGN No      7
OWL DOORSTOP                        7
FRENCH BLUE METAL DOOR SIGN 3       7
RECIPE BOX PANTRY YELLOW DESIGN     7
Amazon                              7
FRENCH BLUE METAL DOOR SIGN 7       6
FRENCH BLUE METAL DOOR SIGN 5       6
FRENCH BLUE METAL DOOR SIGN 6       6
RED KITCHEN SCALES                  6
?                                   6
FRENCH BLUE METAL DOOR SIGN 9       6
MINT KITCHEN SCALES                 6
Name: count, dtype: int64

Sample:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
1988,536550,85044,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2024,536552,20950,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom
2025,536553,37461,NaN,3,2010-12-01 14:35:00,0.0,NaN,United Kingdom
2026,536554,84670,NaN,23,2010-12-01 14:35:00,0.0,NaN,United Kingdom
4348,536765,84952C,NaN,19,2010-12-02 14:43:00,0.0,NaN,United Kingdom
6391,536941,22734,amazon,20,2010-12-03 12:08:00,0.0,NaN,United Kingdom
6392,536942,22139,amazon,15,2010-12-03 12:08:00,0.0,NaN,United Kingdom
7187,536995,35951,NaN,57,2010-12-03 15:29:00,0.0,NaN,United Kingdom
7191,536999,21421,NaN,110,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7194,537002,21651,NaN,70,2010-12-03 15:33:00,0.0,NaN,United Kingdom
9302,537197,22841,ROUND CAKE TIN VINTAGE GREEN,1,2010-12-05 14:02:00,0.0,12647.0,Germany
12008,537361,21777,NaN,5,2010-12-06 12:34:00,0.0,NaN,United Kingdom
13263,537430,85215,NaN,120,2010-12-06 16:05:00,0.0,NaN,United Kingdom
13959,537436,84270,NaN,7,2010-12-06 17:00:00,0.0,NaN,United Kingdom
13960,537437,90167,NaN,10,2010-12-06 17:00:00,0.0,NaN,United Kingdom

In [28]:
# Inspect zero-price rows with negative quantities

zero_price_negative = zero_price[zero_price["Quantity"] < 0]

print("Zero-price + negative quantity:", len(zero_price_negative))

print("\nDescriptions:")
print(zero_price_negative["Description"].value_counts().head(20))

print("\nSample:")
display(zero_price_negative.head(20))

Zero-price + negative quantity: 1336

Descriptions:
Description
check                         120
damages                        45
damaged                        42
?                              41
sold as set on dotcom          20
Damaged                        14
thrown away                     9
Unsaleable, destroyed.          9
??                              7
damages?                        5
wet damaged                     5
ebay                            5
smashed                         4
missing                         3
CHECK                           3
wet pallet                      3
Dotcom sales                    2
reverse 21/5/10 adjustment      2
counted                         2
crushed                         2
Name: count, dtype: int64

Sample:

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
2406,536589,21777,NaN,-10,2010-12-01 16:50:00,0.0,NaN,United Kingdom
4347,536764,84952C,NaN,-38,2010-12-02 14:42:00,0.0,NaN,United Kingdom
7188,536996,22712,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7189,536997,22028,NaN,-20,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7190,536998,85067,NaN,-6,2010-12-03 15:30:00,0.0,NaN,United Kingdom
7192,537000,21414,NaN,-22,2010-12-03 15:32:00,0.0,NaN,United Kingdom
7193,537001,21653,NaN,-6,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7195,537003,85126,NaN,-2,2010-12-03 15:33:00,0.0,NaN,United Kingdom
7196,537004,21814,NaN,-30,2010-12-03 15:34:00,0.0,NaN,United Kingdom
7197,537005,21692,NaN,-70,2010-12-03 15:35:00,0.0,NaN,United Kingdom
7198,537006,21648,NaN,-130,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7199,537007,21172,NaN,-80,2010-12-03 15:36:00,0.0,NaN,United Kingdom
7200,537008,21161,NaN,-120,2010-12-03 15:37:00,0.0,NaN,United Kingdom
7201,537009,84534B,NaN,-80,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7202,537010,22162,NaN,-40,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7203,537011,22139,NaN,-5,2010-12-03 15:38:00,0.0,NaN,United Kingdom
7204,537012,21535,NaN,-12,2010-12-03 15:39:00,0.0,NaN,United Kingdom
7205,537013,35965,NaN,-25,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7206,537014,21040,NaN,-20,2010-12-03 15:40:00,0.0,NaN,United Kingdom
7207,537015,37464,NaN,-14,2010-12-03 15:41:00,0.0,NaN,United Kingdom

In [29]:
# ==========================================
# STEP 2: CLEAN THE DATA
# ==========================================

# Make a copy of the original dataset
clean_df = df.copy()

print("Original rows:", len(clean_df))

# 1. Remove duplicate rows
clean_df = clean_df.drop_duplicates()

print("After removing duplicates:", len(clean_df))

# 2. Remove rows with missing Description
clean_df = clean_df.dropna(subset=["Description"])

print("After removing missing descriptions:", len(clean_df))

# 3. Remove cancelled invoices
clean_df = clean_df[
    ~clean_df["InvoiceNo"].astype(str).str.startswith("C")
]

print("After removing cancelled invoices:", len(clean_df))

# 4. Remove negative quantities
clean_df = clean_df[clean_df["Quantity"] > 0]

print("After removing negative/zero quantities:", len(clean_df))

# 5. Remove zero or negative prices
clean_df = clean_df[clean_df["UnitPrice"] > 0]

print("After removing invalid prices:", len(clean_df))

print("\nFinal cleaned shape:", clean_df.shape)

Original rows: 541909
After removing duplicates: 536641
After removing missing descriptions: 535187
After removing cancelled invoices: 525936
After removing negative/zero quantities: 525462
After removing invalid prices: 524878

Final cleaned shape: (524878, 8)

In [30]:
# ==========================================
# STEP 3: VALIDATE CLEANED DATA
# ==========================================

print("Missing values:")
print(clean_df.isnull().sum())

print("\nDuplicate rows:")
print(clean_df.duplicated().sum())

print("\nNegative quantities:")
print((clean_df["Quantity"] < 0).sum())

print("\nZero quantities:")
print((clean_df["Quantity"] == 0).sum())

print("\nInvalid prices (<= 0):")
print((clean_df["UnitPrice"] <= 0).sum())

print("\nCancelled invoices:")
print(
    clean_df["InvoiceNo"]
    .astype(str)
    .str.startswith("C")
    .sum()
)

Missing values:
InvoiceNo           0
StockCode           0
Description         0
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     132186
Country             0
dtype: int64

Duplicate rows:
0

Negative quantities:
0

Zero quantities:
0

Invalid prices (<= 0):
0

Cancelled invoices:
0

In [31]:
import os

# Make sure the processed folder exists
os.makedirs("data/processed", exist_ok=True)

# Save cleaned dataset
output_path = "data/processed/online_retail_cleaned.csv"

clean_df.to_csv(output_path, index=False)

print("Cleaned dataset saved successfully!")
print("Location:", output_path)

# Check file size
file_size_mb = os.path.getsize(output_path) / (1024 * 1024)
print(f"File size: {file_size_mb:.2f} MB")

Cleaned dataset saved successfully!
Location: data/processed/online_retail_cleaned.csv
File size: 44.91 MB

In [32]:
print("Data types:")
print(clean_df.dtypes)

print("\nDataset shape:")
print(clean_df.shape)

print("\nNumber of unique values:")
print(clean_df.nunique())

Data types:
InvoiceNo              object
StockCode              object
Description            object
Quantity                int64
InvoiceDate    datetime64[us]
UnitPrice             float64
CustomerID            float64
Country                   str
dtype: object

Dataset shape:
(524878, 8)

Number of unique values:
InvoiceNo      19960
StockCode       3922
Description     4026
Quantity         375
InvoiceDate    18499
UnitPrice       1291
CustomerID      4338
Country           38
dtype: int64